// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWezA4dJvQSi9p8xJV3h32eUEdFWEgjpY',
    appId: '1:896869029601:web:2207da0524656b62ca49a0',
    messagingSenderId: '896869029601',
    projectId: 'isis-3510',
    authDomain: 'isis-3510.firebaseapp.com',
    storageBucket: 'isis-3510.appspot.com',
    measurementId: 'G-1HQ87ME9BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7tzb8pOSCnPg9M_oPCdwytPRvKmgH2Bo',
    appId: '1:896869029601:android:52dd320f00eca7a1ca49a0',
    messagingSenderId: '896869029601',
    projectId: 'isis-3510',
    storageBucket: 'isis-3510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsg4qV25Z52YeCAioGR5CJHUYAaL7zvB4',
    appId: '1:896869029601:ios:b1676c25fcceb85fca49a0',
    messagingSenderId: '896869029601',
    projectId: 'isis-3510',
    storageBucket: 'isis-3510.appspot.com',
    iosBundleId: 'com.example.artlens',
  );
}
